language: python
python:
  - '2.7'
  - '3.6'
  - '3.7'
  - 'pypy'
  - 'pypy3'
cache: pip
install:
  - pip install pip-tools -c requirements.txt
  - pip-sync requirements-dev.txt
script:
  - flake8 *.py
  - pytest run_tests.py
after_success:
  - pip install coveralls
  - pytest run_tests.py --cov flake8_builtins --cov-report term-missing
  - coveralls
